import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ReduxProvider } from "@/providers/ReduxProvider";
import { ThemeProvider } from "@/providers/ThemeProvider";
import { SnackbarProvider } from "@/contexts/SnackbarContext";
import { DateProvider } from "@/providers/DateProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <DateProvider>
          <ReduxProvider>
            <ThemeProvider>
              <SnackbarProvider>{children}</SnackbarProvider>
            </ThemeProvider>
          </ReduxProvider>
        </DateProvider>
      </body>
    </html>
  );
}

